import { Fish } from './Fish.js?v=8'; import { Food } from './Food.js?v=7'; import { Bubble } from './Bubble.js?v=7'; import { ParticleSystem } from './ParticleSystem.js?v=7'; import { drawDecorations } from './Decoration.js?v=8';
import { Fish as FishVisual } from './Fish.js?v=10';
const palettes={coral:['#6ed9f5','#1778c1','#4d3d9a'],cave:['#2f9dd2','#2456a9','#181a64'],night:['#634aaf','#244f99','#211448']};
const blend=(a,b,t)=>{const pa=parseInt(a.slice(1),16),pb=parseInt(b.slice(1),16),r=Math.round((pa>>16)*(1-t)+(pb>>16)*t),g=Math.round(((pa>>8)&255)*(1-t)+((pb>>8)&255)*t),bl=Math.round((pa&255)*(1-t)+(pb&255)*t);return `rgb(${r} ${g} ${bl})`;};
export class Aquarium {
  constructor(canvas,state,audio,onNotice,onChange){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.state=state;this.fish=state.fish.map(f=>new FishVisual(f));this.state.fish=this.fish;this.audio=audio;this.onNotice=onNotice;this.onChange=onChange;this.foods=[];this.bubbles=Array.from({length:16},()=>new Bubble(true));this.particles=new ParticleSystem();this.ripples=[];this.last=0;this.running=true;this.petMode=false;this.lastFeed=0;this.knocks=[];this.lastPetAt=0;this.activeBackground=state.background;this.previousBackground=state.background;this.backgroundMix=1;this.resize();new ResizeObserver(()=>this.resize()).observe(canvas);document.addEventListener('visibilitychange',()=>{this.running=!document.hidden;if(this.running){this.last=performance.now();requestAnimationFrame(t=>this.loop(t));}});requestAnimationFrame(t=>this.loop(t));}
  resize(){const rect=this.canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);this.w=rect.width;this.h=rect.height;this.canvas.width=Math.round(this.w*dpr);this.canvas.height=Math.round(this.h*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);}
  getPoint(event){const r=this.canvas.getBoundingClientRect();return {x:(event.clientX-r.left)/r.width,y:(event.clientY-r.top)/r.height};}
  feed(){const now=performance.now();if(now-this.lastFeed<3500){this.onNotice('食物正在慢慢沉下去，等一等再喂吧。');return;}if(this.foods.length>=3){this.onNotice('缸里还有食物，小鱼们还没吃完。');return;}this.lastFeed=now;this.foods.push(new Food(.2+Math.random()*.6));this.audio.feed();this.onNotice('投下了一小粒鱼食。');}
  pointerDown(event){this.dragStart=this.getPoint(event);this.dragPoint=this.dragStart;this.dragTime=performance.now();this.canvas.setPointerCapture?.(event.pointerId);}
  pointerMove(event){if(!this.dragStart)return;const p=this.getPoint(event),dist=Math.hypot(p.x-this.dragPoint.x,p.y-this.dragPoint.y);this.dragPoint=p;if((this.petMode||dist<.04)&&performance.now()-this.lastPetAt>180){const f=this.fish.find(f=>f.hit(p));if(f&&f.pet(this.particles)){this.lastPetAt=performance.now();this.audio.happy();this.onNotice(`${f.name} 很喜欢你的轻轻抚摸。`);}}}
  pointerUp(event){if(!this.dragStart)return;const p=this.getPoint(event),move=Math.hypot(p.x-this.dragStart.x,p.y-this.dragStart.y),elapsed=performance.now()-this.dragTime;this.dragStart=null;if(move>.035||elapsed>380)return;const f=this.fish.find(f=>f.hit(p));if(f){this.onNotice(f.interact(p,this.particles));this.audio.click();}else{this.knock(p);}}
  knock(p){const now=performance.now();this.ripples.push({...p,age:0});this.audio.ripple();this.knocks=this.knocks.filter(t=>now-t<3500);this.knocks.push(now);this.fish.filter(f=>Math.hypot(f.x-p.x,f.y-p.y)<.32).forEach(f=>f.scare(p));if(this.knocks.length>=4)this.onNotice('小鱼有点害怕，请轻一点。');else this.onNotice('玻璃泛起一圈轻轻的水波。');}
  loop(now){if(!this.running)return;const dt=Math.min(.04,(now-this.last)/1000||.016);this.last=now;this.update(dt);this.draw(now/1000);requestAnimationFrame(t=>this.loop(t));}
  update(dt){if(this.activeBackground!==this.state.background){this.previousBackground=this.activeBackground;this.activeBackground=this.state.background;this.backgroundMix=0;}this.backgroundMix=Math.min(1,this.backgroundMix+dt*.75);const flow=this.state.flow==='high'?3:this.state.flow==='medium'?2:1;const celebrate=(fish)=>{this.particles.spawn(fish.x,fish.y,'heart',4);this.audio.happy();this.onNotice(`${fish.name} 吃得很开心！`);};const world={foods:this.foods,fish:this.fish,flow,onEat:celebrate};this.bubbles.forEach(b=>b.update(dt,flow));this.foods.forEach(food=>food.update(dt));this.fish.forEach(f=>f.update(dt,world));this.foods.forEach(food=>{if(food.dead||food.age<11)return;const nearest=this.fish.reduce((best,fish)=>!best||Math.hypot(fish.x-food.x,fish.y-food.y)<Math.hypot(best.x-food.x,best.y-food.y)?fish:best,null);if(nearest&&(food.age>15||Math.hypot(nearest.x-food.x,nearest.y-food.y)<nearest.radius*2.2)){food.dead=true;nearest.hunger=Math.min(100,nearest.hunger+11);nearest.mood=Math.min(100,nearest.mood+5);nearest.behavior='捡到沉下来的食物';celebrate(nearest);}});this.foods=this.foods.filter(f=>!f.dead&&f.age<18);this.particles.update(dt);this.ripples=this.ripples.filter(r=>(r.age+=dt)<1.2);}
  draw(t){const ctx=this.ctx,w=this.w,h=this.h,old=palettes[this.previousBackground],next=palettes[this.activeBackground],p=old.map((color,i)=>blend(color,next[i],this.backgroundMix));ctx.clearRect(0,0,w,h);const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,p[0]);g.addColorStop(.55,p[1]);g.addColorStop(1,p[2]);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.5,-h*.08,0,w*.5,h*.08,w*.55);glow.addColorStop(0,'#ffffff63');glow.addColorStop(.38,'#c9f3ff19');glow.addColorStop(1,'#c9f3ff00');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
    ctx.save();ctx.globalAlpha=this.state.reducedMotion ? .07 : .11;ctx.strokeStyle='#e9fbff';ctx.lineWidth=Math.max(.8,w*.003);for(let i=0;i<3;i++){ctx.beginPath();for(let x=-10;x<w+18;x+=20){const y=h*(.17+i*.11)+Math.sin(x*.033+t*.75+i)*h*.008;x===-10?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();}ctx.restore();
    for(let i=0;i<14;i++){const x=(i*83%w)+Math.sin(t*.2+i)*3,y=h*(.17+(i*37%53)/100);ctx.fillStyle='#efffff4c';ctx.beginPath();ctx.arc(x,y,1.1,0,Math.PI*2);ctx.fill();}drawDecorations(ctx,w,h,this.state,t);this.bubbles.forEach(b=>b.draw(ctx,w,h));this.foods.forEach(f=>f.draw(ctx,w,h));this.fish.slice().sort((a,b)=>a.y-b.y).forEach(f=>f.draw(ctx,w,h,t));this.ripples.forEach(r=>{ctx.globalAlpha=1-r.age/1.2;ctx.strokeStyle='#e6ffff';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(r.x*w,r.y*h,r.age*w*.22,0,7);ctx.stroke();});this.particles.draw(ctx,w,h);ctx.globalAlpha=1;
    const overlays={day:null,night:'#061c7e66',warm:'#ffba4b35',off:'#070a286e'};if(overlays[this.state.light]){ctx.fillStyle=overlays[this.state.light];ctx.fillRect(0,0,w,h);}if(this.state.light==='night'){const rg=ctx.createRadialGradient(w*.5,h*.2,5,w*.5,h*.3,w*.55);rg.addColorStop(0,'#76ddff29');rg.addColorStop(1,'#76ddff00');ctx.fillStyle=rg;ctx.fillRect(0,0,w,h);}}
}

