import { drawFishAvatar } from '../game/FishRenderer.js';
const labels={redCoral:'红色珊瑚',yellowCoral:'黄色珊瑚',bluePlant:'蓝色水草',greenPlant:'绿色水草',cave:'小石洞',shell:'贝壳',star:'海星',ship:'小沉船',crystal:'发光水晶'};
const color={小黄鱼:'#ffe66d',小蓝鱼:'#72d9ff',小河豚:'#ffd56c',小鳐鱼:'#a89af5',小白鱼:'#f5fbff'};
export class UIManager {
  constructor(state,save,audio,aquarium){this.state=state;this.save=save;this.audio=audio;this.aquarium=aquarium;this.modal=document.querySelector('#modal');this.backdrop=document.querySelector('#modal-backdrop');this.title=document.querySelector('#modal-title');this.content=document.querySelector('#modal-content');this.hint=document.querySelector('#hint');this.bind();this.tickClock();setInterval(()=>this.tickClock(),1000);}
  bind(){const $=s=>document.querySelector(s);$('#feed-button').onclick=()=>this.aquarium.feed();$('#pet-button').onclick=e=>{this.aquarium.petMode=!this.aquarium.petMode;e.currentTarget.classList.toggle('active',this.aquarium.petMode);this.notice(this.aquarium.petMode?'抚摸模式已开启：缓慢划过小鱼。':'抚摸模式已关闭。');this.audio.click();};$('#light-button').onclick=()=>this.showLights();$('#decor-button').onclick=()=>this.showDecor();$('#fish-button').onclick=()=>this.showFish();$('#sound-button').onclick=e=>{this.state.sound=!this.state.sound;this.audio.setEnabled(this.state.sound);e.currentTarget.setAttribute('aria-pressed',String(this.state.sound));e.currentTarget.innerHTML=`<span>♬</span>${this.state.sound?'声音开启':'静音'}`;this.notice(this.state.sound?'原创提示音已开启。':'已保持安静。');this.persist();};$('#settings-button').onclick=()=>this.showSettings();$('#modal-close').onclick=()=>this.close();this.backdrop.onclick=e=>{if(e.target===this.backdrop)this.close();};document.addEventListener('keydown',e=>{if(e.key==='Escape')this.close();});const c=this.aquarium.canvas;c.addEventListener('pointerdown',e=>this.aquarium.pointerDown(e));c.addEventListener('pointermove',e=>this.aquarium.pointerMove(e));c.addEventListener('pointerup',e=>this.aquarium.pointerUp(e));c.addEventListener('pointercancel',e=>this.aquarium.pointerUp(e));}
  tickClock(){document.querySelector('#clock').textContent=new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit'}).format(new Date());document.querySelector('#tank-name').textContent=this.state.tankName;const fish=this.aquarium.fish;const avg=key=>Math.round(fish.reduce((sum,item)=>sum+item[key],0)/fish.length);document.querySelector('#tank-hunger').textContent=avg('hunger');document.querySelector('#tank-mood').textContent=avg('mood');document.querySelector('#tank-bond').textContent=avg('bond');}
  notice(text){this.hint.textContent=text;this.hint.style.opacity='1';clearTimeout(this.hintTimer);this.hintTimer=setTimeout(()=>this.hint.style.opacity='.72',3600);}
  open(title,html,bind){this.title.textContent=title;this.content.innerHTML=html;this.backdrop.hidden=false;bind?.();}
  close(){this.backdrop.hidden=true;this.persist();}
  persist(){this.save.save(this.state);this.tickClock();}
  showLights(){const rows=[['day','日间模式','清澈明亮'],['night','蓝色夜灯','柔和月光'],['warm','暖黄观赏','金色暖光'],['off','关闭主灯','静谧暗蓝']];this.open('灯光与场景',`<div class="option-grid">${rows.map(([v,n,d])=>`<button class="choice light" data-v="${v}" aria-pressed="${this.state.light===v}"><b>${n}</b><br><small>${d}</small></button>`).join('')}</div><h3>背景</h3><div class="option-grid">${[['coral','珊瑚海'],['cave','梦幻蓝洞'],['night','紫色夜海']].map(([v,n])=>`<button class="choice bg" data-v="${v}" aria-pressed="${this.state.background===v}">${n}</button>`).join('')}</div>`,()=>{this.content.querySelectorAll('.light').forEach(b=>b.onclick=()=>{this.state.light=b.dataset.v;this.audio.click();this.showLights();});this.content.querySelectorAll('.bg').forEach(b=>b.onclick=()=>{this.state.background=b.dataset.v;this.audio.click();this.showLights();});});}
  showDecor(){this.open('布置小鱼缸',`<p>点击选择想展示的原创装饰。</p><div class="option-grid">${Object.entries(labels).map(([id,name])=>`<button class="choice decoration" data-id="${id}" aria-pressed="${this.state.decorations[id]}">${name}</button>`).join('')}</div>`,()=>this.content.querySelectorAll('.decoration').forEach(b=>b.onclick=()=>{const id=b.dataset.id;this.state.decorations[id]=!this.state.decorations[id];this.audio.click();this.showDecor();}));}
  showFish(){const bars=(f)=>`<div class="meter"><i style="width:${Math.round(f.hunger)}%"></i></div>`;this.open('小鱼信息',`<div class="fish-list">${this.aquarium.fish.map(f=>`<article class="fish-row"><canvas class="fish-avatar" data-type="${f.type}" width="74" height="74" aria-label="${f.type}头像"></canvas><div><b>${f.name}</b> <small>${f.type}</small><small>饱食 ${Math.round(f.hunger)} · 心情 ${Math.round(f.mood)} · 亲密 ${Math.round(f.bond)}</small>${bars(f)}<small>正在${f.behavior}</small></div><button class="rename" data-id="${f.id}">改名</button></article>`).join('')}</div>`,()=>{this.content.querySelectorAll('.fish-avatar').forEach(canvas=>drawFishAvatar(canvas,canvas.dataset.type));this.content.querySelectorAll('.rename').forEach(b=>b.onclick=()=>{const f=this.aquarium.fish.find(x=>x.id===b.dataset.id);const name=prompt(`给 ${f.name} 换个名字`,f.name);if(name?.trim()){f.name=name.trim().slice(0,12);this.showFish();}});});}
  showSettings(){this.open('设置',`<div class="settings"><label>水流 <select id="flow"><option value="low">低</option><option value="medium">中</option><option value="high">高</option></select></label><label>降低动画强度 <input id="reduce" type="checkbox" ${this.state.reducedMotion?'checked':''}></label><label>鱼缸名称 <button class="rename" id="tank-rename">改名</button></label></div><button class="wide-button danger" id="reset">重置鱼缸</button>`,()=>{const flow=this.content.querySelector('#flow');flow.value=this.state.flow;flow.onchange=()=>{this.state.flow=flow.value;this.audio.click();};this.content.querySelector('#reduce').onchange=e=>this.state.reducedMotion=e.target.checked;this.content.querySelector('#tank-rename').onclick=()=>{const n=prompt('输入鱼缸名称',this.state.tankName);if(n?.trim()){this.state.tankName=n.trim().slice(0,20);this.tickClock();}};this.content.querySelector('#reset').onclick=()=>{if(confirm('确定要重置整个鱼缸吗？所有本地进度都会清除。')&&confirm('请再次确认：真的要重新开始吗？')){this.state=this.save.reset();location.reload();}};});}
}
